name: Run Azure Login with OpenID Connect
on:
  workflow_dispatch:
  push:
    branches:
        - feat/*
        - main

permissions:
  id-token: write
  contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: development
    steps:
      - name: 'Az CLI login'
        uses: azure/login@v1
        with:
            client-id: ${{ secrets.AZURE_CLIENT_ID }}
            tenant-id: ${{ secrets.AZURE_TENANT_ID }}
            subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Echo out a GitHub Actions Secret to the logs
        run: |
          echo "The GitHub Action Secret will be masked:  "
          echo ${{ secrets.DEVELOPER_NAME }}
          echo "Trick to echo GitHub Actions Secret:  "
          echo ${{secrets.DEVELOPER_NAME}} | sed 's/./& /g'

      - name: 'Run Azure CLI commands'
        run: |
            az account show
            az group list
            pwd